services:

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: 1241
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U docker"]
      interval: 5s
      timeout: 5s
      retries: 5

  # ------------------ MIGRATORS ------------------

  migrator-music:
    build: ./music-service/migrator
    depends_on:
      postgres:
        condition: service_healthy
    command: [
      "-path=/migrations",
      "-database=postgresql://docker:1241@postgres:5432/music_db?sslmode=disable",
      "up"
    ]

  migrator-lyrics:
    build: ./lyrics-service/migrator
    depends_on:
      postgres:
        condition: service_healthy
    command: [
      "-path=/migrations",
      "-database=postgresql://docker:1241@postgres:5432/lyrics_db?sslmode=disable",
      "up"
    ]

  # ------------------ SERVICES ------------------

  transcription-service:
    build: ./transcription-service
    container_name: transcription-service
    ports:
      - "5001:5001"
    volumes:
      - whisper_cache:/root/.cache/whisper
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 180s 
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

  music-service:
    build: ./music-service
    ports:
      - "50051:50051"
    env_file:
      - ./music-service/.env
    volumes:
      - ./storage:/app/storage
    depends_on:
      migrator-music:
        condition: service_completed_successfully

  lyrics-service:
    build: ./lyrics-service
    ports:
      - "50052:50052"
    env_file:
      - ./lyrics-service/.env
    volumes:
      - whisper_cache:/root/.cache/whisper
    depends_on:
      migrator-lyrics:
        condition: service_completed_successfully
      transcription-service:
        condition: service_healthy
      

  # ------------------ GATEWAY ------------------

  gateway:
    build: ./gateway
    ports:
      - "9090:8080"
    env_file:
      - ./gateway/.env
    depends_on:
      music-service:
        condition: service_started
      lyrics-service:
        condition: service_started

  # ------------------ FRONTEND ------------------

  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "3000:80"
  #   depends_on:
  #     - gateway

volumes:
  postgres_data:
  whisper_cache: